POST http://localhost:3000/api/auth/sign-in/email
Content-Type: application/json

{
    "email": "ardiansetya123@gmail.com",
    "password" : "password"
}

###
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "Test Note",
    "content": "This is a test note content.",
    "folderId": "4219df3d-d07f-4a9e-97b3-3f15eef9e234"
}


###
GET http://localhost:3000/api/notes
