POST http://localhost:3000/api/auth/sign-in/email
Content-Type: application/json
Origin: http://localhost:3000

{
    "email": "ardiansetya123@gmail.com",
    "password" : "password"
}

###
POST http://localhost:3000/api/auth/sign-up/email
Content-Type: application/json
Origin: http://localhost:3000


{
    "name": "Ardiansetya",
    "email": "ardiansetya123@gmail.com",
    "password": "password",
    "image": "",
    "callbackURL": "",
    "rememberMe": true
}
